### ISSUE TITLE
As an organized user, i can sort contacts by any field

### ISSUE THREAD

**Issue by yunpengn** [CS2103AUG2017-T09-B3/main#10]
so that I can arrrage the output of the display result in the expected way.

**Comment by junyango** [comment]
this will be solved using

https://github.com/CS2103AUG2017-T09-B3/main/pull/121
https://github.com/CS2103AUG2017-T09-B3/main/pull/112
https://github.com/CS2103AUG2017-T09-B3/main/pull/93
