### ISSUE TITLE
Sorting of Persons and Events are case-sensitive

### ISSUE THREAD

**Issue by low5545** [CS2103AUG2017-T09-B3/main#131]
A person named 'ali' should not fall behind a person named 'Xavier'.

**Comment by yunpengn** [comment]
Yes, need to change the sorting method in `UniquePersonList`.

The event module is fine because it is based on time.

**Comment by yunpengn** [comment]
It make senses that the sorting is not case sensitive.

**Comment by yunpengn** [comment]
Suggest using `compareToIgnoreCase(String str)` in the java string default API.


> Compares two strings lexicographically, ignoring case differences. This method returns an integer whose sign is that of calling compareTo with normalized versions of the strings where case differences have been eliminated by calling Character.toLowerCase(Character.toUpperCase(character)) on each character.

Not sure whether this will affect the performance though (but this should not be our concern for now)

See the example [here](https://beginnersbook.com/2013/12/java-string-comparetoignorecase-method-example/).

**Comment by yunpengn** [comment]
The change has been applied here (see https://github.com/CS2103AUG2017-T09-B3/main/pull/124/commits/4df02cef3688a4afcc3bae20d1364d2e10fc4e09)
