### ISSUE TITLE
[Bug] Seemingly randomized order of person properties

### ISSUE THREAD

**Issue by Gideonfu** [CS2103AUG2017-T09-B3/main#141]
![image](https://user-images.githubusercontent.com/31119177/32362902-80410ab0-c0a7-11e7-910a-c55141693da0.png)
![image](https://user-images.githubusercontent.com/31119177/32362914-8e5c9b46-c0a7-11e7-8e95-402bde3ca819.png)

The order of the person particulars on selection seem to be random. It would be a lot neater if the order was fixed.

**Comment by Gideonfu** [comment]
If i edit a contact, the order of person particulars may change as well.

**Comment by yunpengn** [comment]
Hi @Gideonfu ,

<br>

Thanks for your kindly bug reporting!

The properties will be sorted based on the name of the properties now. It will be included in the next release

Again, thanks for your help to make **BoNUS** better.

<br><br>

_BoNUS Development Team_

**Comment by yunpengn** [comment]
Changes https://github.com/CS2103AUG2017-T09-B3/main/pull/147 have been merged in.

Yunpeng
