### ISSUE TITLE
[Bug] Find feature

### ISSUE THREAD

**Issue by Gideonfu** [CS2103AUG2017-T09-B3/main#142]
![image](https://user-images.githubusercontent.com/31119177/32363157-d2b6e624-c0a8-11e7-85dc-ab26df949e9d.png)
![image](https://user-images.githubusercontent.com/31119177/32363170-e378d9a4-c0a8-11e7-902b-a56257db788a.png)

The 'AND' find function does not seem to work. I am still able to find Alex even though I added in the extra address property to find.
Even if it was an 'OR' find function, the extra parameters don't seem to work as well.

**Comment by yunpengn** [comment]
Hi @Gideonfu ,

<br>

Thanks for your kindly bug reporting!

Advance search including `AND` and `OR` search is not included in the current release yet. The `UserGuide` has been updated accordingly.

Again, thanks for your help to make **BoNUS** better.

<br><br>

_BoNUS Development Team_

**Comment by yunpengn** [comment]
Update:

The changes have been merged in.

Yunpeng
