### ISSUE TITLE
As a heavy user, I can store different types of information apart from contacts

### ISSUE THREAD

**Issue by yunpengn** [CS2103AUG2017-T09-B3/main#15]
(other types of information like upcoming tasks, events, etc.) so that I can organise every aspect of my daily life conveniently.

**Comment by junyango** [comment]
this will be solved using 

https://github.com/CS2103AUG2017-T09-B3/main/pull/75
https://github.com/CS2103AUG2017-T09-B3/main/pull/55
https://github.com/CS2103AUG2017-T09-B3/main/pull/79
https://github.com/CS2103AUG2017-T09-B3/main/pull/76
