### ISSUE TITLE
Dates in events are not displayed properly.

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T09-B3/main#150]
Day-Month-Year is not formatted in a readable manner.

![image](https://user-images.githubusercontent.com/22949932/32403324-d1051020-c171-11e7-90e4-51cc6a871b5b.png)

Suggestion:
Display it in DD-MMM_YEAR --> 7 NOV 2017

**Comment by yunpengn** [comment]
Hi @lincredibleJC ,

<br>

Thanks for your kindly bug reporting!

We will investigate this.

Again, thanks for your help to make **BoNUS** better.

<br><br>

_BoNUS Development Team_

**Comment by yunpengn** [comment]
This will be solved using https://github.com/CS2103AUG2017-T09-B3/main/pull/185.

**Comment by yunpengn** [comment]
Close this since https://github.com/CS2103AUG2017-T09-B3/main/pull/185 has been merged in.
