### ISSUE TITLE
Clear command clears both the addressbook and events instead of only the current component

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T09-B3/main#151]
Clear command clears both the addressbook and events instead of only the current component
Clear --all still functions as expected

Steps to reproduce:
Open BoNUSv1.4
click on the events page
enter clear

now both addressbook contacts and events are gone

**Comment by yunpengn** [comment]
Hi @lincredibleJC ,

<br>

Thanks for your kindly bug reporting!

The `UserGuide` has been updated accordingly.

Again, thanks for your help to make **BoNUS** better.

<br><br>

_BoNUS Development Team_

**Comment by yunpengn** [comment]
This will be updated using https://github.com/CS2103AUG2017-T09-B3/main/pull/162

**Comment by yunpengn** [comment]
Close this since https://github.com/CS2103AUG2017-T09-B3/main/pull/162 is merged in.
