### ISSUE TITLE
[Bug]Cant Undo Theme but can redo

### ISSUE THREAD

**Issue by ALim95** [CS2103AUG2017-T09-B3/main#194]
![testgif](https://user-images.githubusercontent.com/31213216/32696577-b0114172-c7b6-11e7-8d4f-d54976bb49d6.gif)

Theme function cant be undone but can be redone as shown

**Comment by junyango** [comment]
Bug will be resolved with 

https://github.com/CS2103AUG2017-T09-B3/main/pull/195

**Comment by junyango** [comment]
Thanks @ALim95 for the bug report! Appreciated 😄

**Comment by yunpengn** [comment]
Close this because https://github.com/CS2103AUG2017-T09-B3/main/pull/195 has been merged in.
