### ISSUE TITLE
As an advanced user, I can use auto-complete

### ISSUE THREAD

**Issue by yunpengn** [CS2103AUG2017-T09-B3/main#22]
so that I can search for any fields easily (without remembering the exact value of that field).

**Comment by yunpengn** [comment]
This issue is related to https://github.com/CS2103AUG2017-T09-B3/main/pull/125

**Comment by junyango** [comment]
closed from https://github.com/CS2103AUG2017-T09-B3/main/pull/125 since its not included in v1.5
