### ISSUE TITLE
As an aesthetic-oriented user, I can set the theme of the UI for the address book

### ISSUE THREAD

**Issue by junyango** [CS2103AUG2017-T09-B3/main#23]
so that i can customise the look of my address book

**Comment by junyango** [comment]
Refer to PR 
https://github.com/CS2103AUG2017-T09-B3/main/pull/166

issue has been resolved

**Comment by yunpengn** [comment]
Close this issue since https://github.com/CS2103AUG2017-T09-B3/main/pull/166 has been merged in.
